Improve CS.
Use "python:latest" insteadof "debian:stable-slim".

Use "timonier/version-lister".

diff --git a/bin/installer b/bin/installer
--- a/bin/installer
+++ b/bin/installer
@@ -1,34 +1,38 @@
 #!/bin/sh
-set -ex
+set -eux
+
+# Check environment
 
 fail() {
-    echo $1 1>&2
-    echo "Usage: $0 [install|uninstall]" 1>&2
+    echo "$1" 1>&2
+    echo "Usage: $(basename "$0") [install|uninstall]" 1>&2
     exit 1
 }
 
-if [ $# -lt 1 ] ; then
+if [ "$#" -lt 1 ] ; then
     fail "Invalid number of arguments."
 fi
 
-if [ $(id -u) -ne 0 ] ; then
+if [ "$(id --user)" -ne 0 ] ; then
     fail "Impossible to prepare the system without root privileges."
 fi
 
-if [ $(uname) != "Linux" ] ; then
+if [ "$(uname)" != "Linux" ] ; then
     fail "Impossible to prepare another operating system than Linux."
 fi
 
-case $1 in
+# Run installer
+
+case "$1" in
     install )
-        curl -sLo /usr/local/bin/sshuttle "https://github.com/timonier/sshuttle/raw/master/bin/sshuttle"
+        curl --location --output /usr/local/bin/sshuttle "https://github.com/timonier/sshuttle/raw/master/bin/sshuttle"
         chmod +x /usr/local/bin/sshuttle
     ;;
 
     uninstall )
-        rm -f /usr/local/bin/sshuttle
+        rm --force /usr/local/bin/sshuttle
     ;;
 
     * )
-        fail "Argument $1 is invalid."
+        fail "Argument \"$1\" is invalid."
 esac
